$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        0:{
            items:2,
            nav:true
        },
        650:{
            items:3,
            nav:false
        },
        900:{
            items:4,
            nav:false
        },
        1100:{
            items:5,
            nav:true,
            loop:false
        }
    }
	});
});